name: zzkit_flutter
description: "A useful Flutter package project."
version: 0.1.0
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3
  shimmer: ^3.0.0
  webview_flutter: ^4.7.0
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh: ^2.0.0
  device_info_plus: 9.1.2 # Gradle指定Java11
  crypto: ^3.0.3
  flutter_easyloading: ^3.0.5
  flutter_markdown: ^0.7.1
  flutter_keyboard_visibility: ^6.0.0
  cupertino_icons: ^1.0.6
  event_bus: ^2.0.0
  # 相机相册 Begin
  # 需要Android、iOS权限配置的
  wechat_assets_picker: ^9.0.3
  wechat_camera_picker: ^4.2.1 
  photo_manager: ^3.0.0
  # 相机相册 End
  characters: ^1.3.0
  # 列表和加载相关 Begin
  easy_refresh: ^3.3.5+1
  pull_to_refresh_notification: ^3.1.0
  loading_more_list: ^6.0.0
  extended_nested_scroll_view: ^6.2.1
  visibility_detector: ^0.4.0+2
  # 列表和加载相关 End


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    # assets-generator-begin
    # assets/img/*
    - assets/img/ic_nav_back_black.png
    - assets/img/ic_nav_back_white.png
    - assets/img/ic_nav_close_black.png
    - assets/img/ic_nav_forward_black.png
    - assets/img/ic_nav_forward_gray.png
    - assets/img/ic_nav_notice.png
    - assets/img/ic_placeholder_image.png
    - assets/img/ic_placeholder_no_coupon.png
    - assets/img/ic_placeholder_no_data.png
    - assets/img/ic_placeholder_no_network.png
    - assets/img/ic_scroll_to_top.png
    - assets/img/ic_textfield_delete.png
    - assets/img/ic_textfield_password_off.png
    - assets/img/ic_textfield_password_on.png
    - assets/img/ic_transparent.png
    # assets-generator-end

